server:
  port: 20001

eureka:
  instance:
    hostname: server1

  client:
    # 表示是否注册自身到eureka服务器
    # register-with-eureka: false

    # 是否从eureka上获取注册信息
    # fetch-registry: false

    service-url:
      defaultZone: http://server2:20002/eureka/
