server:
  port: 20002

eureka:
  instance:
    hostname: server2

  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://server1:20001/eureka/
